version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userDb
    ports:
      - "5432:5432"


  artemis:
    container_name: activeMQ
    image: vromero/activemq-artemis
    restart: always
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=password
    ports:
      - "8161:8161"
      - "61616:61616"

  redis:
    container_name: redisCacheContainer
    image: redis/redis-stack  #redis:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"



